apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1

  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: irfandyjip89/microservices_comments
---
apiVersion: v1
kind: Service
metadata:
  name: comments-srv # This name is used to connect to our "comments" service. uRL -> http://comments-srv:4000/events
spec:
  type: ClusterIP
  selector:
    app: comments
  ports:
    - name: comments
      protocol: TCP
      port: 4001
      targetPort: 4001