# Step 4: Run `kubectl apply -f event-bus-depl.yaml`
# Check if the `event-bus-depl` already exist with `kubectl get deployments` or `kubectl get pods`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1

  # This is related to the 'template'
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: irfandyjip89/microservices_event-bus
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv # This name is used to connect to our "event-bus" service. uRL -> http://event-bus-srv:4000/events
spec:
  type: ClusterIP
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005