# Step 5: Rerun `kubectl rollout restart deployment posts-depl`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1

  # This is related to the 'template'
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: irfandyjip89/microservices_posts
