# Register the service by running `kubectl apply -f posts-srv.yaml`
# You can then check if the service has listed correctly by running
# `kubectl get services`
apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts # Will look for the template.metadata.labels "app: posts" in `posts-depl.yaml`, it will look for all the "app" that is labelled as "posts"
  ports:
    - name: posts
      protocol: TCP
      port: 4000 # The port that is a bridge between the computer and the outside world
      targetPort: 4000 # The port that is a bridge between the `post` and the computer