# Step 5: Rerun `kubectl rollout restart deployment posts-depl`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1

  # This is related to the 'template'
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: irfandyjip89/microservices_posts
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv # This name is used to connect to our "posts" service. uRL -> http://posts-clusterip-srv:4000/posts
spec:
  type: ClusterIP
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000